[package]
name = "rust-oss-template-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "命令行入口"

[lints]
workspace = true

[[bin]]
name = "rust-oss-template"
path = "src/main.rs"

[dependencies]
clap.workspace = true
oss-core.workspace = true
